import pytest
from django.contrib.auth import get_user_model

from authentication.core.exceptions import InvalidTokenError
from authentication.core.tokens import (
    decode_uid,
    encode_uid,
    email_verification_token_generator,
    password_reset_token_generator,
)
from users.tests.factories import UserFactory

User = get_user_model()


@pytest.mark.django_db
def test_uid_encoding_decoding() -> None:
    user = UserFactory()
    encoded = encode_uid(user.pk)
    decoded = decode_uid(encoded)
    assert decoded == str(user.pk)


def test_uid_decoding_invalid() -> None:
    with pytest.raises(InvalidTokenError):
        decode_uid("invalid-base64-string!!")


@pytest.mark.django_db
def test_token_generators_distinct() -> None:
    user = UserFactory()
    
    reset_token = password_reset_token_generator.make_token(user)
    verify_token = email_verification_token_generator.make_token(user)
    
    # Assert token generated by one cannot be validated by the other
    assert not password_reset_token_generator.check_token(user, verify_token)
    assert not email_verification_token_generator.check_token(user, reset_token)


@pytest.mark.django_db
def test_email_change_invalidates_verification_token() -> None:
    user = UserFactory(email="first@example.com")
    
    verify_token = email_verification_token_generator.make_token(user)
    assert email_verification_token_generator.check_token(user, verify_token)
    
    # Change user's email
    user.email = "second@example.com"
    user.save()
    
    # The old verification token must now be invalid
    assert not email_verification_token_generator.check_token(user, verify_token)
