# Generated by Django 6.0.6 on 2026-06-29 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='user agent')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='last activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The username or email typed by the user.', max_length=255, verbose_name='identifier')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='user agent')),
                ('was_successful', models.BooleanField(db_index=True, verbose_name='was successful')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='failure reason')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['identifier', 'created_at'], name='authenticat_identif_cc1bde_idx'), models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_1dccaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="The OAuth2 provider name (e.g., 'google', 'github').", max_length=50, verbose_name='provider')),
                ('provider_user_id', models.CharField(help_text='The unique user ID returned by the remote provider.', max_length=255, verbose_name='provider user ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
